//
// Generated file, do not edit! Created by nedtool 4.6 from inet/applications/broadcasting/BroadcastingAppBase.msg.
//

#ifndef _INET__BROADCASTING_BROADCASTINGAPPBASE_M_H_
#define _INET__BROADCASTING_BROADCASTINGAPPBASE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace broadcasting {

/**
 * Class generated from <tt>inet/applications/broadcasting/BroadcastingAppBase.msg:19</tt> by nedtool.
 * <pre>
 * packet Hello
 * {
 *     string sender;
 *     int x;
 *     int y;
 * }
 * </pre>
 */
class INET_API Hello : public ::cPacket
{
  protected:
    opp_string sender_var;
    int x_var;
    int y_var;

  private:
    void copy(const Hello& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Hello&);

  public:
    Hello(const char *name=NULL, int kind=0);
    Hello(const Hello& other);
    virtual ~Hello();
    Hello& operator=(const Hello& other);
    virtual Hello *dup() const {return new Hello(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual int getX() const;
    virtual void setX(int x);
    virtual int getY() const;
    virtual void setY(int y);
};

inline void doPacking(cCommBuffer *b, Hello& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Hello& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/applications/broadcasting/BroadcastingAppBase.msg:25</tt> by nedtool.
 * <pre>
 * packet Broadcast
 * {
 *     string id;
 *     string sender;
 *     string payload;
 * }
 * </pre>
 */
class INET_API Broadcast : public ::cPacket
{
  protected:
    opp_string id_var;
    opp_string sender_var;
    opp_string payload_var;

  private:
    void copy(const Broadcast& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Broadcast&);

  public:
    Broadcast(const char *name=NULL, int kind=0);
    Broadcast(const Broadcast& other);
    virtual ~Broadcast();
    Broadcast& operator=(const Broadcast& other);
    virtual Broadcast *dup() const {return new Broadcast(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getId() const;
    virtual void setId(const char * id);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, Broadcast& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Broadcast& obj) {obj.parsimUnpack(b);}

} // namespace broadcasting
} // namespace inet

#endif // ifndef _INET__BROADCASTING_BROADCASTINGAPPBASE_M_H_

