/*
 * generated by Xtext 2.9.0
 */
package fr.labri.tima

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DSLRuntimeModule extends fr.labri.tima.AbstractDSLRuntimeModule {
}
