/*
 * generated by Xtext 2.9.0
 */
package fr.labri.tima


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLStandaloneSetup extends fr.labri.tima.DSLStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
